services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GOLANG_PORT}:${GOLANG_PORT}"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
